spring:
  security:
    oauth2:
      client:
        registration:
          msvc-usuarios-client:
            provider: spring
            client-id: usuarios-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8001/autorized
