apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: msvc-gateway
  name: msvc-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-gateway
  template:
    metadata:
      labels:
        app: msvc-gateway
    spec:
      containers:
        - image: edualdan982/gateway:latest
          name: gateway
          ports:
            - containerPort: 8089
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-gateway
spec:
  ports:
    - port: 8089
      protocol: TCP
      targetPort: 8089
  selector:
    app: msvc-gateway
  type: LoadBalancer