apiVersion: v1
kind: Service
metadata:
  name: msvc-auth
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: msvc-auth
  type: LoadBalancer
  # loadBalancerIP: 172.19.20.10